app/blueprints/tools/__init__.py
from flask import Blueprint

bp = Blueprint('tools', __name__)

from app.blueprints.tools import routes

app/blueprints/tools/routes.py
from flask import render_template, request, jsonify, flash
from flask_login import current_user, login_required
from app.blueprints.tools import bp
from app.models import UserTransfer
from app import db
import pandas as pd
import numpy as np
from data_modelling.team_predict import get_squad_predictions, get_optimal_team_selection
from data_modelling.predictions_retrieve import get_predictions
from data_modelling.transfer_recommend import transfer_recommender, choose_transfer
from data_modelling.data_fetcher import DataFetcher


@bp.route('/team-selector', methods=['GET', 'POST'])
@login_required
def team_selector():
    return render_template(
        'tools/team_selector.html', title='Team Selector')


@bp.route('/predictions', methods=['POST'])
@login_required
def predictions():
    data = get_predictions()
    gameweek = data['next_gameweek']
    team_id = current_user.team_id
    transfers = UserTransfer.query.filter_by(user_id=current_user.id).all()
    transfer_list = []
    for transfer in transfers:
        transfer_list.append([transfer.out_id, transfer.in_id])
    squad = get_squad_predictions(team_id, transfer_list)
    squad['squad_predictions'] = squad['squad_predictions'].rename(
        columns={'position': 'Position', 'first_name': 'First Name',
                 'second_name': 'Second Name',
                 'expected_points': 'Expected Points'}).to_html(index=False,
                                                                columns=['Position', 'First Name', 'Second Name',
                                                                         'Expected Points'],
                                                                classes="table table-striped table-hover table-condensed")
    return jsonify(
        {'gameweek': gameweek, 'squadName': squad['team_name'], 'squadPredictions': squad['squad_predictions']})


@bp.route('/get_optimal_team', methods=['POST'])
@login_required
def get_optimal_team():
    squad_predictions = pd.read_html("""{}""".format(request.form['team']))[0].rename(
        columns={'Position': 'position', 'First Name': 'first_name',
                 'Second Name': 'second_name', 'Expected Points': 'expected_points'})
    squad_predictions.index = squad_predictions.index.rename('id')
    optimal_team = get_optimal_team_selection(squad_predictions)
    return jsonify({'best_score': optimal_team['best_score'],
                    'best_team': optimal_team['best_team'].replace(
                        {'GKP': 100, 'DEF': 101, 'MID': 102, 'FWD': 103}).sort_values(by=['position'])
                   .replace({100: 'GKP', 101: 'DEF', 102: 'MID', 103: 'FWD'}).rename(
                        columns={'position': 'Position', 'first_name': 'First Name',
                                 'second_name': 'Second Name',
                                 'expected_points': 'Expected Points'}).to_html(
                        index=False,
                        classes='table table-striped table-hover table-condensed',
                        columns=['Position', 'First Name', 'Second Name', 'Expected Points'])})


@bp.route('/transfer-recommend', methods=['GET', 'POST'])
@login_required
def transfer_recommend():
    return render_template('tools/transfer_recommend.html',
                           title='Transfer Recommender')


@bp.route('/get_recommended_transfers', methods=['POST'])
@login_required
def get_recommended_transfers():
    team_id, n_trans = request.form['team_id'], int(request.form['n_trans'])
    transfers = UserTransfer.query.filter_by(user_id=current_user.id).all()
    transfer_list = []
    for transfer in transfers:
        transfer_list.append([transfer.out_id, transfer.in_id])
    recommended = transfer_recommender(team_id, n_trans, transfer_list)
    rename_dict = {'out_1_first_name': 'Out', 'in_1_first_name': 'In', 'score': 'New expected score'}
    for i in range(1, n_trans + 1):
        rename_dict['in_{}_second_name'.format(i)] = ''
        rename_dict['out_{}_second_name'.format(i)] = ''
    if n_trans == 2:
        rename_dict['in_2_first_name'] = ''
        rename_dict['out_2_first_name'] = ''
    return jsonify({'recommended':
                        recommended.rename(
                            columns=rename_dict
                        ).to_html(index=False, classes='table table-striped table-hover table-condensed'),
                    'n_trans': n_trans})


@bp.route('/get_new_team', methods=['POST'])
@login_required
def get_new_team():
    n_trans = int(request.form['n_trans'])
    if n_trans == 1:
        out_ids, in_ids = [int(float(request.form['out_id']))], [int(float(request.form['in_id']))]
    else:
        out_ids, in_ids = [int(float(request.form['out_id1'])), int(float(request.form['out_id2']))],\
                                  [int(float(request.form['in_id1'])), int(float(request.form['in_id2']))]
    data = get_predictions()
    predictions = data['predictions']
    transfers = UserTransfer.query.filter_by(user_id=current_user.id).all()
    transfer_list = []
    for transfer in transfers:
        transfer_list.append([transfer.out_id, transfer.in_id])
    squad = get_squad_predictions(current_user.team_id, transfer_list)['squad_predictions']
    new_team = choose_transfer(out_ids, in_ids, squad, predictions)
    return jsonify({'new_team': new_team['best_team'].replace(
        {'GKP': 100, 'DEF': 101, 'MID': 102, 'FWD': 103}).sort_values(by=['position'])
                   .replace({100: 'GKP', 101: 'DEF', 102: 'MID', 103: 'FWD'}).rename(
        columns={'position': 'Position', 'first_name': 'First Name', 'second_name': 'Second Name',
                 'expected_points': 'Expected Points'}
    ).to_html(index=False, classes='table table-striped table-hover table-condensed', columns=['Position', 'First Name',
                                                                                               'Second Name',
                                                                                               'Expected Points']),
                    'best_score': new_team['best_score']})


@bp.route('/custom-transfers', methods=['GET', 'POST'])
@login_required
def custom_transfers():
    return render_template('tools/custom_transfers.html', title='Custom Transfers')


@bp.route('/get-valid-transfers', methods=['POST'])
@login_required
def get_valid_transfers():
    transfers = UserTransfer.query.filter_by(user_id=current_user.id).all()
    transfer_list = []
    for transfer in transfers:
        transfer_list.append([transfer.out_id, transfer.in_id])
    squad_predictions = get_squad_predictions(current_user.team_id, transfer_list)
    current_bank = squad_predictions['bank']
    team_counts = squad_predictions['squad_predictions']['team'].value_counts()
    player_out = pd.DataFrame(
        squad_predictions['squad_predictions'].reset_index().iloc[int(request.form['row']), :]).transpose()
    new_team_counts = pd.DataFrame(team_counts.subtract(
        player_out['team'].value_counts()).fillna(player_out['team'].value_counts()).fillna(
        team_counts))
    forbidden_teams = new_team_counts[new_team_counts.team >= 3].index.values
    allowed_teams = pd.Series(np.setdiff1d(np.arange(1, 21), forbidden_teams))
    team_dict = {
        1: 'ARS',
        2: 'AVL',
        3: 'BOU',
        4: 'BHA',
        5: 'BUR',
        6: 'CHE',
        7: 'CRY',
        8: 'EVE',
        9: 'LEI',
        10: 'LIV',
        11: 'MCI',
        12: 'MUN',
        13: 'NEW',
        14: 'NOR',
        15: 'SHU',
        16: 'SOU',
        17: 'TOT',
        18: 'WAT',
        19: 'WHU',
        20: 'WOL'
    }
    allowed_teams = allowed_teams.map(team_dict)
    player_out_sp = player_out['SP'].values[0]
    retrieve_predictions = get_predictions()
    other_player_predictions = retrieve_predictions['predictions']
    valid_players = other_player_predictions[
        (other_player_predictions.position == player_out.loc[:, 'position'].values[0]) &
        (other_player_predictions.price <= player_out_sp + current_bank) &
        (np.isin(other_player_predictions.team, allowed_teams)) &
        (np.isin(other_player_predictions.index.values,
                 np.setdiff1d(other_player_predictions.index.values,
                              squad_predictions['squad_predictions'].reset_index()['id'].values)))]
    return jsonify({'out_id': str(player_out['id'].values[0]), 'validPlayers': valid_players.rename(
        columns={'position': 'Position', 'first_name': 'First Name',
                 'second_name': 'Second Name', 'price': 'Price', 'team': 'Team', 'expected_points': 'Expected Points'}
    ).to_html(classes='table table-striped table-hover table-condensed', columns=['Position', 'Team', 'First Name',
                                                                                  'Second Name', 'Price',
                                                                                  'Expected Points']),
                    })


@bp.route('/add_transfer', methods=['POST'])
@login_required
def add_transfer():
    data = get_predictions()
    gameweek = data['next_gameweek']
    transfer = UserTransfer(user_id=current_user.id, out_id=request.form['out_id'], in_id=request.form['in_id'],
                            gameweek=gameweek)
    db.session.add(transfer)
    db.session.commit()
    flash('Transfer successfully added')
    return jsonify({})


@bp.route('/get_custom_transfers', methods=['POST'])
@login_required
def get_custom_transfers():
    data = get_predictions()
    gameweek = data['next_gameweek']
    transfers = UserTransfer.query.filter_by(user_id=current_user.id, gameweek=gameweek).all()
    transfer_list = []
    for transfer in transfers:
        transfer_list.append([transfer.out_id, transfer.in_id])

app/templates/tools/custom_transfers.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="{{ url_for('static', filename='js/tools/custom_transfers.js') }}"></script>

<h1>Custom Transfers</h1>
<br>
<div class="btn-group" role="group">
    <button class="btn btn-lg btn-primary" id="transfers_in">Add Transfer</button>
    <button class="btn btn-lg btn-default" id="transfers_out">View Transfers</button>
    <button class="btn btn-default btn-lg" onclick="location.href = '{{ url_for('tools.team_selector') }}';">
        Team Selector</button>
    <button class="btn btn-default btn-lg" onclick="location.href = '{{ url_for('tools.transfer_recommend') }}';">
        Transfer Recommender</button>
</div>
<hr>
<div class="remove" id="transfers_table"></div>

<div class="remove" id="remove"></div>

<div class="make" id="out"></div>
<div class="make" id="in"></div>
<div class="row make">
    <div class="col col-md-1" id="confirm"></div>
    <div class="col col-md-1" id="cancel"></div>
</div>
<div class="make" id="choose_in_out">
    <h4>Choose a player to transfer out:</h4>
</div>
<br>
<div class="make" id="out_table"></div>

<div class="make" id="in_table"></div>

<div class="make" id="show_more"></div>

{% endblock %}

app/templates/tools/team_selector.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type='text/javascript' src="{{ url_for('static', filename='js/tools/team_selector.js') }}"></script>

<h1>
    Team Selector
</h1>
<br>
<div class="btn-group" role="group">
    <button class="btn btn-default btn-lg" onclick="location.href = '{{ url_for('tools.custom_transfers') }}';">
        Custom Transfers</button>
    <button class="btn btn-default btn-lg" onclick="location.href = '{{ url_for('tools.transfer_recommend') }}';">
        Transfer Recommender</button>
</div>
<hr>

<div id="top_heading"></div>

<br>

<div id="table"></div>

<br>

<div id="heading"></div>

<div id="tableId"></div>

<br>
<div id="not_right">
    <h4>Is our data out of date?</h4>
    <br>
    <button class="btn btn-md btn-default" onclick="location.href = '{{ url_for('tools.custom_transfers') }}';">Add / Reset Custom Transfers</button>
</div>

{% endblock %}

app/templates/tools/transfer_recommend.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/tools/transfer_recommend.js') }}"></script>

<h1>
    Transfer recommender for {{ current_user.username }}:
</h1>
<br>
<div class="btn-group" role="group">
    <button class="btn btn-default btn-lg" onclick="location.href = '{{ url_for('tools.custom_transfers') }}';">
        Custom Transfers</button>
    <button class="btn btn-default btn-lg" onclick="location.href = '{{ url_for('tools.team_selector') }}';">
        Team Selector</button>
</div>
<hr>
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label>Number of Free Transfers</label>
            <select id="nTrans" class="form-control">
                <option>1</option>
                <option>2</option>
            </select>
        </div>
        <div id="submit">
            <a class="btn btn-default btn-md" href="javascript:get_recommended_transfers('#submit');">Get recommended transfers</a>
        </div>
    </div>
</div>
<br><br>
<div id="info">
    <h3>Recommended Transfers</h3>
    <p>Click a recommended transfer to see your new optimal team selection.</p>
</div>
<div id="recommended">

</div>
<a class="btn btn-default btn-md" id="moreTransfers">Show more</a>
<br><br>
<div id="new_stuff">
    <div id="new_score">

    </div>
    <div id="new_team">

    </div>
</div>
{% endblock %}