app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.blueprints.main import routes

app/blueprints/main/routes.py
from flask import render_template, request, jsonify, g, current_app
from flask_login import current_user
from flask_babel import get_locale
from datetime import datetime
from app.blueprints.main import bp
from app import db
import time
from data_modelling.predictions_retrieve import get_predictions


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
    g.locale = str(get_locale())


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('main/index.html', title='Home')


@bp.route('/index-predictions', methods=['POST'])
def index_predictions():
    data = get_predictions()
    gameweek = data['next_gameweek']
    predictions = data['predictions']
    return jsonify({'gameweek': gameweek, 'predictions': predictions.rename(
        columns={'position': 'Position', 'first_name': 'First Name',
                 'second_name': 'Second Name',
                 'expected_points': 'Expected Points', 'team': 'Team',
                 'value': 'Value', 'price': 'Price'}).to_html(
        index=False, classes="table table-responsive table-hover table-striped", table_id="index_table",
        columns=['Position', 'Team', 'First Name', 'Second Name', 'Price', 'Expected Points', 'Value'])})


@bp.route('/get_sorted_table', methods=['POST'])
def get_sorted_table():
    data = get_predictions()
    predictions = data['predictions']
    columns = ['position', 'team', 'first_name', 'second_name', 'price', 'expected_points', 'value']
    columns_ascending = {'position': True,
                         'team': True,
                         'first_name': True,
                         'second_name': True,
                         'price': False,
                         'expected_points': False,
                         'value': False}
    column = columns[int(request.form['column']) - 1]
    ascending = columns_ascending[column]
    return jsonify({'predictions': predictions.sort_values(column, ascending=ascending).rename(
        columns={'position': 'Position', 'first_name': 'First Name',
                 'second_name': 'Second Name',
                 'expected_points': 'Expected Points', 'team': 'Team',
                 'value': 'Value', 'price': 'Price'}).to_html(
        index=False, classes="table table-responsive table-hover table-striped", table_id="index_table",
        columns=['Position', 'Team', 'First Name', 'Second Name', 'Price', 'Expected Points', 'Value'])})


@bp.route('/about')
def about():
    return render_template('main/about.html', title='About')

app/templates/main/about.html
{% extends "base.html" %}

{% block app_content %}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script>
    $(document).ready(function() {
        show_getting_started();
    });

    function show_getting_started() {
        $('#getting_started').show();
        $('#the_model').hide();
        $('#tools').hide();
        $('#forum').hide();
        $('#getting_started_nav').addClass('active');
        $('#the_model_nav').removeClass('active');
        $('#tools_nav').removeClass('active');
        $('#forum_nav').removeClass('active');
    };

    function show_model() {
        $('#getting_started').hide();
        $('#the_model').show();
        $('#tools').hide();
        $('#forum').hide();
        $('#getting_started_nav').removeClass('active')
        $('#the_model_nav').addClass('active');
        $('#tools_nav').removeClass('active');
        $('#forum_nav').removeClass('active');
    };

    function show_tools() {
        $('#getting_started').hide();
        $('#the_model').hide();
        $('#tools').show();
        $('#forum').hide();
        $('#getting_started_nav').removeClass('active');
        $('#the_model_nav').removeClass('active');
        $('#tools_nav').addClass('active');
        $('#forum_nav').removeClass('active');
    };

    function show_forum() {
        $('#getting_started').hide();
        $('#the_model').hide();
        $('#tools').hide();
        $('#forum').show();
        $('#getting_started_nav').removeClass('active');
        $('#the_model_nav').removeClass('active');
        $('#tools_nav').removeClass('active');
        $('#forum_nav').addClass('active');
    };
</script>

<h1>About</h1>
<br>
<ul class="nav nav-tabs">
    <li id="getting_started_nav" role="presentation" class="active"><a href="javascript:show_getting_started();">
        Getting Started
    </a></li>
    <li id="the_model_nav" role="presentation"><a href="javascript:show_model();">The Model</a></li>
    <li id="tools_nav" role="presentation"><a href="javascript:show_tools();">Tools</a></li>
    <li id="forum_nav" role="presentation"><a href="javascript:show_forum();">Forum</a></li>
</ul>
<div id="getting_started">
    <h2>Getting Started</h2>
    <br>
    {% if current_user.is_anonymous %}
    <p>To get started with FPLHelper, <a href="{{ url_for('auth.register') }}">register</a> for an account, or
        <a href="{{ url_for('auth.login') }}">login</a>!</p>
    {% else %}
    <p>Now you have an account with FPLHelper, you can do more than just explore all the predictions the algorithm has
    made: you can apply them to your team!</p>
    {% endif %}
</div>

<div id="the_model">
    <h2>The Model</h2>
    <br>
    <p>The model used to predict the expected points metric is "random forest" regression which you can read more about
    <a href="https://en.wikipedia.org/wiki/Random_forest" target="_blank">here</a>.</p>
    <p>The data on which it is modelled is collected from the Fantasy Premier League API and updated on a gameweek by
    gameweek basis. Naturally, as more data is collected, the model will improve as the season progresses.</p>
</div>

<div id="tools">
    <h2>Tools</h2>
    <br>
    <h3><a href="{{ url_for('tools.team_selector') }}" style="color:#000000">Team Selector</a></h3>
    <br>
    <p>The team selector takes the players you picked last week, and gives an optimal team selection based on the
    expected points metric. In order to add transfers which you may have already made so that your squad is up to date,
        please add <i>custom transfers</i>.</p>
    <hr>
    <h3><a href="{{ url_for('tools.custom_transfers') }}" style="color:#000000">Custom Transfers</a></h3>
    <br>
    <p>The custom transfers tool allows you to add any transfers you have made already, or ones you will potentially make.
    This allows more accurate team selection through the team selection tool, and transfer recommendation using the transfer
    recommender tool.</p>
    <hr>
    <h3><a href="{{ url_for('tools.transfer_recommend') }}" style="color:#000000">Transfer Recommender</a></h3>
    <br>
    <p>The transfer recommender goes through each player in your team, and checks potential transfers and how they
    change the total expected score for your team. The transfers which improve your expected score the most will be
    recommended first.</p>
</div>

<div id="forum">
    <h3>Using the Forum</h3>
    <br>
    <p>The <a href="{{ url_for('forum.index') }}">forum</a> consists of threads, and posts within each thread.</p>
    <p> <b>Threads</b> are recommended to be created for larger
        topics, e.g. player selection for the upcoming gameweek.</p>
    <p><b>Posts</b> within each thread should stay relevant to the topic
    of the thread! It is a great way to interact with other users, and share advice/talking points.</p>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

<title>FPLHelper</title>

{% block app_content %}
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/main/index.js') }}"></script>

<div class="jumbotron">
    {% if current_user.is_authenticated %}
  <h1>Welcome to FPLHelper, {{ current_user.username }}!</h1>
      <p>Helping you get the edge in Fantasy Premier League</p>
      <p><a class="btn btn-primary btn-lg" href="{{ url_for('main.about') }}" role="button">Learn more</a>
          <a class="btn btn-primary btn-lg" href="{{ url_for('tools.team_selector') }}" role="button">Team Selector</a>
          <a class="btn btn-primary btn-lg" href="{{ url_for('tools.transfer_recommend') }}" role="button">Transfer Recommender</a>
          <a class="btn btn-primary btn-lg" href="{{ url_for('tools.custom_transfers') }}" role="button">Custom Transfers</a>
      </p>
    {% else %}
    <h1>Welcome to FPLHelper!</h1>
    <p>Helping you get the edge in Fantasy Premier League</p>
      <p><a class="btn btn-primary btn-lg" href="{{ url_for('main.about') }}" role="button">Learn more</a>
          <a class="btn btn-primary btn-lg" href="{{ url_for('auth.register') }}" role="button">Register</a>
          <a class="btn btn-primary btn-lg" href="{{ url_for('auth.login') }}" role="button">Login</a>
      </p>
    {% endif %}

</div>

<img id="loading_predictions" src="{{ url_for('static', filename='images/loading.gif') }}">

<div id="main_heading"></div>

<br>
<div class="row" id="filters">
    <div class="col-md-4">
        <h4>Filters:</h4>
        <div class="form-group">
            <img src="">
            <label>Position</label>
            <select class="filter form-control" name="Position" id="position_filter">
                <option id="any_pos" value="">Any</option>
                <option id="gkp" value="GKP">Goalkeeper</option>
                <option id="def" value="DEF">Defender</option>
                <option id="mid" value="MID">Midfielder</option>
                <option id="fwd" value="FWD">Forward</option>
            </select>
        </div>
        <div class="form-group">
            <label>Team</label>
            <select class="filter form-control" name="Team" id="team_filter">
                <option value="">Any</option>
                <option value="ARS">Arsenal</option>
                <option value="AVL">Aston Villa</option>
                <option value="BOU">Bournemouth</option>
                <option value="BHA">Brighton</option>
                <option value="BUR">Burnley</option>
                <option value="CHE">Chelsea</option>
                <option value="CRY">Crystal Palace</option>
                <option value="EVE">Everton</option>
                <option value="LEI">Leicester</option>
                <option value="LIV">Liverpool</option>
                <option value="MCI">Man City</option>
                <option value="MUN">Man United</option>
                <option value="NEW">Newcastle</option>
                <option value="NOR">Norwich</option>
                <option value="SHU">Sheffield United</option>
                <option value="SOU">Southampton</option>
                <option value="TOT">Spurs</option>
                <option value="WAT">Watford</option>
                <option value="WHU">West Ham</option>
                <option value="WOL">Wolves</option>
            </select>
        </div>
        <div class="form-group">
            <label>Minimum Price</label>
            <select class="filter form-control" name="Min Price" id="min_price_filter">
                <option value="0">Any</option>
                <option value="4.0">4.0</option>
                <option value="4.5">4.5</option>
                <option value="5.0">5.0</option>
                <option value="5.5">5.5</option>
                <option value="6.0">6.0</option>
                <option value="6.5">6.5</option>
                <option value="7.0">7.0</option>
                <option value="7.5">7.5</option>
                <option value="8.0">8.0</option>
                <option value="8.5">8.5</option>
                <option value="9.0">9.0</option>
                <option value="9.5">9.0</option>
                <option value="10.0">10.0</option>
                <option value="10.5">10.5</option>
                <option value="11.0">11.0</option>
                <option value="11.5">11.5</option>
                <option value="12.0">12.0</option>
                <option value="12.5">12.5</option>
                <option value="13.0">13.0</option>
            </select>
        </div>
        <div class="form-group">
            <label>Maximum Price</label>
            <select class="filter form-control" name="Max Price" id="max_price_filter">
                <option value="100">Any</option>
                <option value="4.0">4.0</option>
                <option value="4.5">4.5</option>
                <option value="5.0">5.0</option>
                <option value="5.5">5.5</option>
                <option value="6.0">6.0</option>
                <option value="6.5">6.5</option>
                <option value="7.0">7.0</option>
                <option value="7.5">7.5</option>
                <option value="8.0">8.0</option>
                <option value="8.5">8.5</option>
                <option value="9.0">9.0</option>
                <option value="9.5">9.0</option>
                <option value="10.0">10.0</option>
                <option value="10.5">10.5</option>
                <option value="11.0">11.0</option>
                <option value="11.5">11.5</option>
                <option value="12.0">12.0</option>
                <option value="12.5">12.5</option>
                <option value="13.0">13.0</option>
            </select>
        </div>
        <div id="no_results_div" class="alert alert-info">No results found.</div>
    </div>
    <div id="table_div" class="col-md-8">
        <div id="inside_table_div">

        </div>
        <div id="buttons">
            <a class="btn btn-default btn-md" id="moreRows">Show more</a>
            <a class="btn btn-default btn-md" id="toTop">Back to top</a>
        </div>
    </div>
</div>
<br>
{% endblock %}